add a3 sample
GoogleCloudPlatform/ai-infra-cluster-provisioning pull request #248
Opened 2023-06-30 20:55 UTC by stevenBorisko

2023-06-30 21:09 UTC, Chris113113 requested changes
Tell don't ask

2023-06-30 21:09 UTC, Chris113113 commented on samples/mig-with-container/a3_multi_nic_network/README.md
> +Please find detailed set up instruction for docker image
Tell, don't ask

2023-06-30 21:09 UTC, Chris113113 commented on samples/mig-with-container/a3_multi_nic_network/main.tf
> +  source = "github.com/GoogleCloudPlatform/ai-infra-cluster-provisioning//terraform/modules/cluster/mig"
`provisioning//terraform` intentional?

2023-06-30 21:09 UTC, Chris113113 commented on samples/mig-with-container/a3_multi_nic_network/README.md
> +directory of your local machine. Then follow the below instructions to create the cluster.
Add line about which tfvar values need to be set, i.e. project_id, remote_mount

2023-07-06 15:12 UTC, stevenBorisko commented on samples/mig-with-container/a3_multi_nic_network/main.tf
> +  source = "github.com/GoogleCloudPlatform/ai-infra-cluster-provisioning//terraform/modules/cluster/mig"
unfortunately, it is

2023-07-06 16:28 UTC, sdlin approved these changes

2023-07-06 17:48 UTC, Chris113113 approved these changes

2023-07-06 17:49 UTC, merged