Supporting minimal terraform verbosity for running with LLM pipeline.
GoogleCloudPlatform/ai-infra-cluster-provisioning pull request #61
Opened 2023-02-07 23:43 UTC by soumyapani

2023-02-07 23:49 UTC, abdallag commented on scripts/_terraform_util.sh
> +    if [[ ! -z "$SHOW_PROXY_URL" && "${SHOW_PROXY_URL,,}" == "no" ]]; then
You can use -n instead of '! -z'

2023-02-07 23:49 UTC, abdallag commented on scripts/_terraform_util.sh
> +            # change terraform verbosity based on SHOW_PROXY_URL environment variable.
It would be better to have a separate environment variable to control logging verbosity

2023-02-08 00:37 UTC, DmitryKakurin requested changes

2023-02-08 00:37 UTC, DmitryKakurin commented on README.md
> +19. ***MINIMIZE_TERRAFORM_LOGGING***. This controls the verbosity of terraform logs. When any value is set for this parameter, the terraform output is reditrected to a local file and not printed on s
```suggestion
19. ***MINIMIZE_TERRAFORM_LOGGING***. This controls the verbosity of terraform logs. When any value is set for this parameter, the terraform output is redirected to a local file and not printed on syserr. The log file is then uploaded to storage account. Any value can be set for this parameter, e.g.: yes, true.
```

2023-02-08 00:37 UTC, DmitryKakurin commented on scripts/_terraform_util.sh
> +                echo "Redirecting terraform destroy output to $TERRAFORM_LOG_PATH."
```suggestion
                echo "Redirecting 'terraform destroy' output to $TERRAFORM_LOG_PATH."
```

2023-02-08 00:37 UTC, DmitryKakurin commented on scripts/_terraform_util.sh
> +        gsutil -m cp $TERRAFORM_LOG_PATH gs://$TF_BUCKET_NAME/$TF_DEPLOYMENT_PATH/$NAME_PREFIX-terraformlog.txt
Perhaps `terraform.log` for a file name? log.txt seems redundant.

2023-02-08 00:39 UTC, abdallag approved these changes

2023-02-08 00:44 UTC, DmitryKakurin approved these changes

2023-02-08 00:47 UTC, merged